version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      #target: build
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - migrate

  postgres:
    container_name: test-lamoda-postgres
    image: postgres:14.8-alpine3.18
    env_file:
      - .env
    volumes:
      - testdb-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  migrate:
    container_name: test-lamoda-migrate
    image: "migrate/migrate:v4.17.1"
    depends_on:
      - postgres
    volumes:
      - "./migrations:/migrations"
    command: ["-path", "/migrations/psql/", "-database", "$SERVICE_DB_DSN", "up"]

volumes:
  testdb-data: