POST http://localhost:8080/reserve/create
Content-Type: application/json
Accept: application/json

{
    "id": "12345",
    "jsonrpc": "2.0",
    "method": "reserve.create",
    "params": {
        "skus": ["NikeClassicM", "AdidasPoloM", "hello2"]
    }
}