POST http://localhost:8080/store/balance
Content-Type: application/json
Accept: application/json

{
    "id": "12345",
    "jsonrpc": "2.0",
    "method": "store.balance",
    "params": {
        "store_id": 1
    }
}